Add data in authors.yml and blog in _posts
IEEE-NITK/blog pull request #17
Opened 2021-01-06 18:04 UTC by Dragonado

I have created a new branch called "chaithanya-shyam" and  added my data in authors.yml and I have created a blog of ~1500 words on the topic of "Elegant Algorithms using Randomization". Please review my PR.

2021-01-10 10:31 UTC, adharshkamath requested changes

2021-01-10 10:31 UTC, adharshkamath commented on _posts/2021-01-06-Elegant-Algorithms-Using-Randomization.md
> +---
add  `use_math: true` here for Mathjax

2021-01-11 16:10 UTC, Dragonado commented on _posts/2021-01-06-Elegant-Algorithms-Using-Randomization.md
> +---
I just added it. I did not build the blog locally last time, I have done it now and it seems okay.

2021-01-11 16:13 UTC, adharshkamath commented
Please resolve the merge conflict

2021-01-11 16:21 UTC, Dragonado commented
Conflict in authors.yml has been resolved.

2021-01-11 16:24 UTC, adharshkamath approved these changes

2021-01-11 16:25 UTC, adharshkamath commented
Remove the build files please

2021-01-11 16:33 UTC, Dragonado commented
I have removed all build files. Only 2 files have changes that is authors.yml and my blog

2021-01-11 16:49 UTC, adharshkamath approved these changes

2021-01-11 19:28 UTC, merged