New article: Playing Blackjack with Reinforcement Learning
IEEE-NITK/blog pull request #21
Opened 2021-01-06 20:22 UTC by Shreya301

2021-05-05 13:48 UTC, vrn25 requested changes

2021-05-05 13:48 UTC, vrn25 commented on _posts/2021-01-06-Playing-Blackjack-Optimally-with-Reinforcemen-Learning.md
> +
1. Change Gamma to $\gamma$
2. Reframe the last line as - how much it prioritizes rewards it receives in the near future compared to what it would receive later.

2021-05-05 13:48 UTC, vrn25 commented on _posts/2021-01-06-Playing-Blackjack-Optimally-with-Reinforcemen-Learning.md
> +
1. Policy is a function that maps a state to an action or a distribution over actions. 
2. Why is the state-value function not as good when we do not have a model of the environment?

2021-05-05 13:48 UTC, vrn25 commented on _posts/2021-01-06-Playing-Blackjack-Optimally-with-Reinforcemen-Learning.md
> +
1. "which is what an agent would also do using dynamic programming", change it to "one of the ways this can be done is through dynamic programming"
2. "ϵ fraction of the times", can change it to "with a probability ϵ"

2021-05-05 13:48 UTC, vrn25 commented on _posts/2021-01-06-Playing-Blackjack-Optimally-with-Reinforcemen-Learning.md
> +
Maybe include the diagram from GPI from sutton and barto?
will be more illustrative to the audience

2021-05-05 13:48 UTC, vrn25 commented on _posts/2021-01-06-Playing-Blackjack-Optimally-with-Reinforcemen-Learning.md
> +
instead of "mean return", it would be correct to say expected return

2021-05-05 13:48 UTC, vrn25 commented on _posts/2021-01-06-Playing-Blackjack-Optimally-with-Reinforcemen-Learning.md
> +$$
1. "such that it's stochastic" what is "it" here? Q function? Does it make sense for Q to be stochastic? If it is, then it means if we input the same reward and action to the Q function, it can give a different result. Why should that be? Maybe you're referring to the policy being stochastic because that would make more sense. 
2. gamma -> \gamma

2021-05-05 13:48 UTC, vrn25 commented on _posts/2021-01-06-Playing-Blackjack-Optimally-with-Reinforcemen-Learning.md
> +
It would be better to elaborate why you think a personal assistant robot comes under continuing tasks
Different people can have different perspectives

2021-05-05 13:48 UTC, vrn25 commented on _posts/2021-01-06-Playing-Blackjack-Optimally-with-Reinforcemen-Learning.md
> +
"by looking at the next state" -> "by looking at the **value of** next state"

2021-05-05 13:48 UTC, vrn25 commented on _posts/2021-01-06-Playing-Blackjack-Optimally-with-Reinforcemen-Learning.md
> +
Maybe instead of model use some other word
the word "model" has a special meaning in reinforcement learning hence we should not use it for referring to something else

2021-05-05 13:48 UTC, vrn25 commented on _posts/2021-01-06-Playing-Blackjack-Optimally-with-Reinforcemen-Learning.md
> +A blog that covers the methods mentioned here: https://lilianweng.github.io/lil-log/2018/02/19/a-long-peek-into-reinforcement-learning.html
Well written! Just do the changes and then it's good to go

2021-05-05 16:53 UTC, Shreya301 commented on _posts/2021-01-06-Playing-Blackjack-Optimally-with-Reinforcemen-Learning.md
> +
I added a small explanation

2021-05-05 16:56 UTC, Shreya301 commented on _posts/2021-01-06-Playing-Blackjack-Optimally-with-Reinforcemen-Learning.md
> +
I have made it estimate of the model

2021-05-05 20:34 UTC, vrn25 requested changes

2021-05-05 20:34 UTC, vrn25 commented on _posts/2021-01-06-Playing-Blackjack-Optimally-with-Reinforcemen-Learning.md
> +$$
"(here we just assign all values to 0)" you'll have to change this also
if all probability of all actions is 0, what will an agent pick? You can just randomly initialize the policy or maybe initialize all probabilities to np.ones([num_states, num_actions])/num_actions indicating that each action has an equal probability of getting selected

2021-05-05 20:34 UTC, vrn25 commented on _posts/2021-01-06-Playing-Blackjack-Optimally-with-Reinforcemen-Learning.md
> +
A model itself is an estimate of how the environment works. It is weird to say the estimate of an estimate. 
Plus we should not use model here as we are in a model-free setting and we directly interact with the environment to gain experience and update value functions and policies Make it:

"We estimate the Q-values only from the current reward, and use our current estimate of the values of the next state to predict the future reward. While this is faster, our targets are based on our estimation itself, making it unstable."

2021-05-05 20:34 UTC, vrn25 commented on _posts/2021-01-06-Playing-Blackjack-Optimally-with-Reinforcemen-Learning.md
> +
Why is there a requirement for the model? Suppose the agent just has access to the V function. It can directly interact with the environment to find what state to go to (based on the reward it gets). In fact, that's what is done when you estimate the Q function from the V function. Having a model or not does not matter.
 
There is nothing good or bad as such in having only a V function or only a Q function. Each of them can be derived from the other so it does not matter which one you have. It is just that the Q function gives a little more information about what could happen and the V function summarizes that information. 
I would suggest remove this description for the state-value function and just write its definition.

2021-05-14 20:41 UTC, Shreya301 commented on _posts/2021-01-06-Playing-Blackjack-Optimally-with-Reinforcemen-Learning.md
> +
Ah understood. I replaced it with your suggestion.

2021-07-11 06:29 UTC, closed without merging