New Article: Neural Style Transfer
IEEE-NITK/blog pull request #26
Opened 2021-01-08 14:03 UTC by dharmicksai

In this blog, I tried to explain component by component of the working of a Style Transfer Model which produces a styled image given  style and content image

2021-01-08 17:02 UTC, geekswaroop requested changes

2021-01-08 17:02 UTC, geekswaroop commented on _posts/2021-01-07-Neural-style-transfer.md
> +Total Loss given content representation p, style representation a, styled image representation x:
Use latex here.

2021-01-08 17:02 UTC, geekswaroop commented on _posts/2021-01-07-Neural-style-transfer.md
> +We can see that many paintings share some common features like brush strokes etc, conditional Instance normalisation helps us to encode style into an embedding and a common image transformation netwo
Uniform capitalisation.

2021-01-08 17:02 UTC, geekswaroop commented on _posts/2021-01-07-Neural-style-transfer.md
> +The Image Transformation Network Details are given in this [paper](https://arxiv.org/pdf/1610.07629.pdf) For implementing Multi-style Transfer
Uniform capitalisation.

2021-01-09 04:52 UTC, dharmicksai commented on _posts/2021-01-07-Neural-style-transfer.md
> +title: "Why GraphQL is a big thing"
sorry my bad will correct it

2021-01-09 05:28 UTC, dharmicksai commented
hey, I added latex and fixed the typo. Please do look again

2021-01-09 09:31 UTC, geekswaroop approved these changes
LGTM, Good Job on the article :)

2021-05-05 19:18 UTC, merged