New article: SEEFOOD
IEEE-NITK/blog pull request #78
Opened 2022-04-12 12:45 UTC by vinayakj02

Recreating the SEE-FOOD app from Silicon Valley using Transfer Learning in PyTorch

2022-08-25 08:25 UTC, pranavdv requested changes
Content is good overall. Some changes in the format are required.

2022-08-25 08:25 UTC, pranavdv commented on _posts/2022-04-12-SEEFOOD.md
> +SEEFOOD is an application which basically predicts if an image is an image of a hot-dog or not. This is based on the model used in the [HBO's Silicon Valley ](https://www.youtube.com/watch?v=vIci3C4J
Mention here also that the rest of the article is a tutorial on building the model. Also mention here what you expect the reader to know already (like CNNs, PyTorch, transfer learning etc).

2022-08-25 08:25 UTC, pranavdv commented on _posts/2022-04-12-SEEFOOD.md
> +![image](/blog/assets/img/SEEFOOD/image1.png)
Don't add screenshots of the code. Write it directly in backticks. Same for all the screenshots following this as well. Cell outputs that have images can be added directly.

2022-08-28 07:55 UTC, vinayakj02 commented on _posts/2022-04-12-SEEFOOD.md
> +SEEFOOD is an application which basically predicts if an image is an image of a hot-dog or not. This is based on the model used in the [HBO's Silicon Valley ](https://www.youtube.com/watch?v=vIci3C4J
Done

2022-08-28 07:55 UTC, vinayakj02 commented on _posts/2022-04-12-SEEFOOD.md
> +![image](/blog/assets/img/SEEFOOD/image1.png)
Done

2022-08-28 08:45 UTC, pranavdv approved these changes
nit: center align all images and gifs.
LGTM, nice work.

2022-09-04 10:44 UTC, merged