Harish Gumnur Blog
IEEE-NITK/blog pull request #93
Opened 2022-04-16 09:34 UTC by harry7337

Introduction to Deep Learning

2022-05-28 03:44 UTC, nishant-nayak commented on _posts/2022-04-12-Intro-To-Deep-Learning.md
> +Overcoming challenges with DL
Was this meant to be a heading?

2022-05-28 03:48 UTC, nishant-nayak requested changes
Looks pretty good! If the one comment I provided was not meant to be a heading, it looks good for publishing.

2022-06-11 03:27 UTC, nishant-nayak approved these changes
Looks good to merge!

2022-06-11 03:29 UTC, nishant-nayak requested changes
Didn't see the image change last time around, please fix this

2022-06-11 03:29 UTC, nishant-nayak commented on _posts/2022-04-12-Intro-To-Deep-Learning.md
> +![GO](/blog/assets/img/intro-to-dl/go.jped)
Please fix this image link, should be `go.jpeg`

2022-06-11 15:11 UTC, harry7337 reviewed
Resolved image link

2022-06-12 17:31 UTC, nishant-nayak approved these changes

2022-07-06 15:23 UTC, merged